### ISSUE TITLE
Would you run a example from the code ?

### ISSUE THREAD

**Issue by eshinesimida** [joren485/Facebook-Location-OSINT#2]

**Comment by joren485** [comment]
Could you please be more specific?

**Comment by eshinesimida** [comment]
user = sys.argv[1]
username = sys.argv[2]
password = sys.argv[3]

would you set detail value to run the code?Thank you

**Comment by joren485** [comment]
You run it like this `python2 get_location.py user username password`.
Please refer to the [docs](https://docs.python.org/2/library/sys.html) for any python specific questions.
