### ISSUE TITLE
I am fixing it!

### ISSUE THREAD

**Issue by powersem2007** [joren485/Facebook-Location-OSINT#5]
Hello again i am trying to fix the code i fixed many things but now i see an very strange error
on line 63 where is "locale" defined? bc i get the error
TypeError "locale"

if you want to help me it is wonderfull my dc is SemegordenTheDev#6897 if needed

**Comment by joren485** [comment]
As I said in #4, this project is no longer maintained. It is old code that worked with the Facebook APIs of 6 year ago.
